listen = *, ::
protocols = imap
mail_location = maildir:~/Maildir
ssl = yes
ssl_cert = </etc/lab/tls/cert.pem
ssl_key = </etc/lab/tls/key.pem
disable_plaintext_auth = yes
auth_mechanisms = plain login
log_path = /var/log/dovecot.log
