[udp4]
type=transport
protocol=udp
bind=0.0.0.0:5060

[udp6]
type=transport
protocol=udp
bind=[::]:5060

[lab]
type=endpoint
context=lab
disallow=all
allow=ulaw,opus
auth=lab
aors=lab
direct_media=no
rtp_symmetric=yes
rtp_ipv6=yes

[lab]
type=auth
auth_type=userpass
username=lab
password=voip-throwaway

[lab]
type=aor
max_contacts=20
remove_existing=yes
