"""initial tables

revision: 0001
revises: 
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('urls', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('bundle_version', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=64), nullable=False),
    sa.Column('timings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('counts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('risk', sa.Integer(), nullable=True),
    sa.Column('risk_band', sa.String(length=16), nullable=True),
    sa.Column('replay', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_created_at'), 'analyses', ['created_at'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('tunnel_idx', sa.Integer(), nullable=True),
    sa.Column('check_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('standard', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('threats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_analysis_id'), 'findings', ['analysis_id'], unique=False)
    op.create_table('replay_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('t_end', sa.Float(), nullable=False),
    sa.Column('packets', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replay_chunks_analysis_id'), 'replay_chunks', ['analysis_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('tunnel_idx', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('band', sa.String(length=16), nullable=False),
    sa.Column('breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_analysis_id'), 'risk_scores', ['analysis_id'], unique=False)
    op.create_table('threats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('threat_id', sa.String(length=16), nullable=False),
    sa.Column('threat', sa.String(length=200), nullable=False),
    sa.Column('likelihood', sa.Integer(), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('tunnels', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('findings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threats_analysis_id'), 'threats', ['analysis_id'], unique=False)
    op.create_table('tunnels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('initiator', sa.String(length=64), nullable=True),
    sa.Column('responder', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('direction_from', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('esp_packets', sa.Integer(), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=True),
    sa.Column('end_s', sa.Float(), nullable=True),
    sa.Column('has_traffic', sa.Boolean(), nullable=False),
    sa.Column('esp_suite_probabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tunnels_analysis_id'), 'tunnels', ['analysis_id'], unique=False)
    op.create_table('config_facts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tunnel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['tunnel_id'], ['tunnels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_facts_tunnel_id'), 'config_facts', ['tunnel_id'], unique=False)
    op.create_table('session_shares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tunnel_id', sa.Integer(), nullable=False),
    sa.Column('app', sa.String(length=16), nullable=False),
    sa.Column('byte_share', sa.Float(), nullable=False),
    sa.Column('byte_rounded', sa.Integer(), nullable=False),
    sa.Column('error_pp', sa.Float(), nullable=True),
    sa.Column('active_share', sa.Float(), nullable=True),
    sa.Column('active_rounded', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tunnel_id'], ['tunnels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_shares_tunnel_id'), 'session_shares', ['tunnel_id'], unique=False)
    op.create_table('windows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tunnel_id', sa.Integer(), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('pair', sa.Integer(), nullable=False),
    sa.Column('esp_bytes', sa.Float(), nullable=False),
    sa.Column('packets', sa.Integer(), nullable=False),
    sa.Column('present', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('probabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('shares', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['tunnel_id'], ['tunnels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_windows_tunnel_id'), 'windows', ['tunnel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_windows_tunnel_id'), table_name='windows')
    op.drop_table('windows')
    op.drop_index(op.f('ix_session_shares_tunnel_id'), table_name='session_shares')
    op.drop_table('session_shares')
    op.drop_index(op.f('ix_config_facts_tunnel_id'), table_name='config_facts')
    op.drop_table('config_facts')
    op.drop_index(op.f('ix_tunnels_analysis_id'), table_name='tunnels')
    op.drop_table('tunnels')
    op.drop_index(op.f('ix_threats_analysis_id'), table_name='threats')
    op.drop_table('threats')
    op.drop_index(op.f('ix_risk_scores_analysis_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_replay_chunks_analysis_id'), table_name='replay_chunks')
    op.drop_table('replay_chunks')
    op.drop_index(op.f('ix_findings_analysis_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_analyses_created_at'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
